### ISSUE TITLE
Can't login or create a new account

### ISSUE THREAD

**Issue by enilsen16** [enilsen16/Ordr#72]

**Comment by DeirdreAllison** [comment]
Sorry Erik - I'm going to be finishing the Angular front end on this soon, I've been at a sticking point and finally recruited a friend to help. I would look at the changes from the PR Matt merged into master...you could log in before that. I should have time to look into this next week.

**Comment by enilsen16** [comment]
I don't think those changes were pushed to heroku though.

**Comment by DeirdreAllison** [comment]
Good point. If nothing else, I can set up login with devise/angular unless you have a different idea?

**Comment by enilsen16** [comment]
nope do that, @aqlien's oath idea never worked out anyway. Do you have access to CF's slack?

**Comment by DeirdreAllison** [comment]
I do not.

**Comment by enilsen16** [comment]
Hm... I just asked how to bring more alumni in. They are phasing out gitter because its not very private.

**Comment by DeirdreAllison** [comment]
Ok, thanks. I looked at this app a little today and something is very wrong. I was able to create a new account by running the master branch locally and that seems to be working, but I'm getting a lot of weird behavior in the create_api branch that wasn't happening before.

**Comment by enilsen16** [comment]
Hmmm... Let me know what you find. I talked to Ryan about slack, I guess you need to contact Ryan or Brook for an invite. It will be easier to talk in there rather than github comments. :+1:
